"""create all tables

Revision ID: 09655b1f84c7
Revises: d2de875cebce
Create Date: 2026-02-10 13:05:32.226703
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09655b1f84c7'
down_revision: Union[str, None] = 'd2de875cebce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bow_type', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setup_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brace_height', sa.Float(), nullable=True),
    sa.Column('tiller', sa.Float(), nullable=True),
    sa.Column('draw_weight', sa.Float(), nullable=True),
    sa.Column('draw_length', sa.Float(), nullable=True),
    sa.Column('arrow_foc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_template_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.String(length=50), nullable=True),
    sa.Column('num_ends', sa.Integer(), nullable=False),
    sa.Column('arrows_per_end', sa.Integer(), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=False),
    sa.Column('value_score_map', sa.JSON(), nullable=False),
    sa.Column('max_score_per_arrow', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['round_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('total_x_count', sa.Integer(), nullable=False),
    sa.Column('total_arrows', sa.Integer(), nullable=False),
    sa.Column('setup_profile_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['setup_profile_id'], ['setup_profiles.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['round_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setup_equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('setup_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setup_id'], ['setup_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('end_number', sa.Integer(), nullable=False),
    sa.Column('end_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scoring_sessions.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['round_template_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('end_id', sa.UUID(), nullable=False),
    sa.Column('arrow_number', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.String(length=5), nullable=False),
    sa.Column('score_numeric', sa.Integer(), nullable=False),
    sa.Column('x_pos', sa.Float(), nullable=True),
    sa.Column('y_pos', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['end_id'], ['ends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrows')
    op.drop_table('ends')
    op.drop_table('setup_equipment')
    op.drop_table('scoring_sessions')
    op.drop_table('round_template_stages')
    op.drop_table('setup_profiles')
    op.drop_table('round_templates')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
