"""add email verification profile public and share token

Revision ID: 459225dbf800
Revises: 09655b1f84c7
Create Date: 2026-02-11 13:25:02.428238
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '459225dbf800'
down_revision: Union[str, None] = '09655b1f84c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_sessions', sa.Column('share_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_scoring_sessions_share_token'), 'scoring_sessions', ['share_token'], unique=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_public')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_scoring_sessions_share_token'), table_name='scoring_sessions')
    op.drop_column('scoring_sessions', 'share_token')
    # ### end Alembic commands ###
