package auth

import "testing"

func TestDecodePythonGeneratedToken(t *testing.T) {
	// Token generated by Python's jose.jwt.encode with the dev secret key.
	// Claims: {sub: "550e8400-e29b-41d4-a716-446655440000", type: "access", exp: ...}
	pythonToken := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTBlODQwMC1lMjliLTQxZDQtYTcxNi00NDY2NTU0NDAwMDAiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczNzY4OTkxfQ.oGjrntR6v2h3xzhx1fpmljT-4rh-C5q0SMbf5I-BRpg"

	claims, err := DecodeToken(pythonToken, testSecret)
	if err != nil {
		t.Fatalf("decode Python token: %v", err)
	}

	expectedSub := "550e8400-e29b-41d4-a716-446655440000"
	if claims.Subject != expectedSub {
		t.Errorf("subject = %q, want %q", claims.Subject, expectedSub)
	}
	if claims.Type != "access" {
		t.Errorf("type = %q, want %q", claims.Type, "access")
	}
}
