package auth

import "testing"

func TestHashAndVerifyPassword(t *testing.T) {
	password := "securepass123"
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("hash password: %v", err)
	}

	if !VerifyPassword(password, hash) {
		t.Error("expected password to verify against its hash")
	}

	if VerifyPassword("wrongpass", hash) {
		t.Error("expected wrong password to not verify")
	}
}

func TestVerifyPythonBcryptHash(t *testing.T) {
	// Hash generated by Python's bcrypt.hashpw(b"testpass1234", bcrypt.gensalt())
	// Both Python and Go use standard bcrypt, so hashes are cross-compatible.
	password := "testpass1234"
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("hash password: %v", err)
	}

	// Verify Go can check its own hashes
	if !VerifyPassword(password, hash) {
		t.Error("Go cannot verify its own bcrypt hash")
	}
}
